
package healthprofile.storage.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthProfileService", targetNamespace = "http://service.storage.healthprofile/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthProfileService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addMeasureToHealthprofile", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.AddMeasureToHealthprofile")
    @ResponseWrapper(localName = "addMeasureToHealthprofileResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.AddMeasureToHealthprofileResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/addMeasureToHealthprofileRequest", output = "http://service.storage.healthprofile/HealthProfileService/addMeasureToHealthprofileResponse")
    public void addMeasureToHealthprofile(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Measure arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.CreatePersonResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/createPersonRequest", output = "http://service.storage.healthprofile/HealthProfileService/createPersonResponse")
    public Integer createPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns healthprofile.storage.service.Measure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMeasure", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetMeasure")
    @ResponseWrapper(localName = "getMeasureResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetMeasureResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/getMeasureRequest", output = "http://service.storage.healthprofile/HealthProfileService/getMeasureResponse")
    public Measure getMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns healthprofile.storage.service.Measure
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMeasure", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.UpdateMeasure")
    @ResponseWrapper(localName = "updateMeasureResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.UpdateMeasureResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/updateMeasureRequest", output = "http://service.storage.healthprofile/HealthProfileService/updateMeasureResponse")
    public Measure updateMeasure(
        @WebParam(name = "arg0", targetNamespace = "")
        Measure arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns healthprofile.storage.service.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetPersonById")
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetPersonByIdResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/getPersonByIdRequest", output = "http://service.storage.healthprofile/HealthProfileService/getPersonByIdResponse")
    public Person getPersonById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<healthprofile.storage.service.Measure>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMeasureHistory", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetMeasureHistory")
    @ResponseWrapper(localName = "getMeasureHistoryResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetMeasureHistoryResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/getMeasureHistoryRequest", output = "http://service.storage.healthprofile/HealthProfileService/getMeasureHistoryResponse")
    public List<Measure> getMeasureHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<healthprofile.storage.service.Measure>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHealthProfile", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetHealthProfile")
    @ResponseWrapper(localName = "getHealthProfileResponse", targetNamespace = "http://service.storage.healthprofile/", className = "healthprofile.storage.service.GetHealthProfileResponse")
    @Action(input = "http://service.storage.healthprofile/HealthProfileService/getHealthProfileRequest", output = "http://service.storage.healthprofile/HealthProfileService/getHealthProfileResponse")
    public List<Measure> getHealthProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
