
package advisor.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdvisorServiceService", targetNamespace = "http://service.advisor/", wsdlLocation = "http://idesmm-advisor.herokuapp.com/advisorservice?wsdl")
public class AdvisorServiceService
    extends Service
{

    private final static URL ADVISORSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADVISORSERVICESERVICE_EXCEPTION;
    private final static QName ADVISORSERVICESERVICE_QNAME = new QName("http://service.advisor/", "AdvisorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://idesmm-advisor.herokuapp.com/advisorservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADVISORSERVICESERVICE_WSDL_LOCATION = url;
        ADVISORSERVICESERVICE_EXCEPTION = e;
    }

    public AdvisorServiceService() {
        super(__getWsdlLocation(), ADVISORSERVICESERVICE_QNAME);
    }

    public AdvisorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADVISORSERVICESERVICE_QNAME, features);
    }

    public AdvisorServiceService(URL wsdlLocation) {
        super(wsdlLocation, ADVISORSERVICESERVICE_QNAME);
    }

    public AdvisorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADVISORSERVICESERVICE_QNAME, features);
    }

    public AdvisorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdvisorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdvisorService
     */
    @WebEndpoint(name = "AdvisorServicePort")
    public AdvisorService getAdvisorServicePort() {
        return super.getPort(new QName("http://service.advisor/", "AdvisorServicePort"), AdvisorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdvisorService
     */
    @WebEndpoint(name = "AdvisorServicePort")
    public AdvisorService getAdvisorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.advisor/", "AdvisorServicePort"), AdvisorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADVISORSERVICESERVICE_EXCEPTION!= null) {
            throw ADVISORSERVICESERVICE_EXCEPTION;
        }
        return ADVISORSERVICESERVICE_WSDL_LOCATION;
    }

}
