
package advisor.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import healthprofile.storage.service.Person;
import recipestorage.service.Recipe;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdvisorService", targetNamespace = "http://service.advisor/")
@XmlSeeAlso({
    advisor.service.ObjectFactory.class,
    healthprofile.storage.service.ObjectFactory.class,
    recipestorage.service.ObjectFactory.class
})
public interface AdvisorService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeightAdvice", targetNamespace = "http://service.advisor/", className = "advisor.service.GetWeightAdvice")
    @ResponseWrapper(localName = "getWeightAdviceResponse", targetNamespace = "http://service.advisor/", className = "advisor.service.GetWeightAdviceResponse")
    @Action(input = "http://service.advisor/AdvisorService/getWeightAdviceRequest", output = "http://service.advisor/AdvisorService/getWeightAdviceResponse")
    public String getWeightAdvice(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecommendedIntake", targetNamespace = "http://service.advisor/", className = "advisor.service.GetRecommendedIntake")
    @ResponseWrapper(localName = "getRecommendedIntakeResponse", targetNamespace = "http://service.advisor/", className = "advisor.service.GetRecommendedIntakeResponse")
    @Action(input = "http://service.advisor/AdvisorService/getRecommendedIntakeRequest", output = "http://service.advisor/AdvisorService/getRecommendedIntakeResponse")
    public Double getRecommendedIntake(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMealAdvice", targetNamespace = "http://service.advisor/", className = "advisor.service.GetMealAdvice")
    @ResponseWrapper(localName = "getMealAdviceResponse", targetNamespace = "http://service.advisor/", className = "advisor.service.GetMealAdviceResponse")
    @Action(input = "http://service.advisor/AdvisorService/getMealAdviceRequest", output = "http://service.advisor/AdvisorService/getMealAdviceResponse")
    public String getMealAdvice(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Recipe> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFitnessAdvice", targetNamespace = "http://service.advisor/", className = "advisor.service.GetFitnessAdvice")
    @ResponseWrapper(localName = "getFitnessAdviceResponse", targetNamespace = "http://service.advisor/", className = "advisor.service.GetFitnessAdviceResponse")
    @Action(input = "http://service.advisor/AdvisorService/getFitnessAdviceRequest", output = "http://service.advisor/AdvisorService/getFitnessAdviceResponse")
    public String getFitnessAdvice(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
